logging:
  path: /data/log/leisure-member-api

server:
  servlet:
    context-path: /leisure-member-api

leisure-member:
  ribbon:
    listOfServers: http://127.0.0.1:8080/leisure-member,http://47.105.97.16:8080/leisure-member
